#!/usr/bin/env python3
"""B21.1 helper: capture and summarize the B20 LF guidance patch.

This script records the current diff in external/daps against an upstream ref,
checks whether the patch applies to a clean checkout when requested, extracts
source snippets around B20_LF env-var guards, and writes a markdown report draft.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple


def run(cmd: Sequence[str], *, cwd: Path | None = None, check: bool = False) -> Tuple[int, str, str]:
    proc = subprocess.run(
        list(cmd),
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(f"command failed {proc.returncode}: {' '.join(cmd)}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}")
    return proc.returncode, proc.stdout, proc.stderr


def split_items(text: str) -> List[str]:
    return [x.strip() for x in str(text).split(",") if x.strip()]


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def collect_env_snippets(daps_root: Path, files: Sequence[str], context: int = 8) -> str:
    needles = ["B20_LF", "LF_ENABLE", "LF_ALPHA", "LF_FRAC", "LF_RADIUS", "lowfreq", "low_freq"]
    blocks: List[str] = []
    for rel in files:
        path = daps_root / rel
        if not path.exists() or not path.is_file():
            continue
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        hit_lines = []
        for idx, line in enumerate(lines):
            if any(n in line for n in needles):
                hit_lines.append(idx)
        if not hit_lines:
            continue
        ranges: List[Tuple[int, int]] = []
        for idx in hit_lines:
            start = max(0, idx - context)
            end = min(len(lines), idx + context + 1)
            if ranges and start <= ranges[-1][1] + 1:
                ranges[-1] = (ranges[-1][0], max(ranges[-1][1], end))
            else:
                ranges.append((start, end))
        for start, end in ranges:
            blocks.append(f"## {path} lines {start + 1}-{end}")
            blocks.append("```python")
            for i in range(start, end):
                blocks.append(f"{i + 1:04d}: {lines[i]}")
            blocks.append("```")
            blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def maybe_clean_apply_check(daps_root: Path, upstream_ref: str, patch_path: Path, clean_check_dir: str, refresh: bool) -> Dict[str, object]:
    if not clean_check_dir:
        return {"status": "skipped", "reason": "--clean_check_dir not supplied"}
    clean = Path(os.path.expandvars(os.path.expanduser(clean_check_dir)))
    if clean.exists() and refresh:
        shutil.rmtree(clean)
    if not clean.exists():
        code, out, err = run(["git", "clone", str(daps_root), str(clean)])
        if code != 0:
            return {"status": "clone_failed", "returncode": code, "stdout": out, "stderr": err}
    code, out, err = run(["git", "checkout", upstream_ref], cwd=clean)
    if code != 0:
        return {"status": "checkout_failed", "returncode": code, "stdout": out, "stderr": err}
    code, out, err = run(["git", "apply", "--check", str(patch_path.resolve())], cwd=clean)
    return {"status": "pass" if code == 0 else "fail", "returncode": code, "stdout": out, "stderr": err, "clean_dir": str(clean)}


def render_report(
    repo_root: Path,
    daps_root: Path,
    upstream_ref: str,
    diff_paths: Sequence[str],
    patch_path: Path,
    status_text: str,
    diff_text: str,
    snippets: str,
    apply_check: Dict[str, object],
) -> str:
    env_names = sorted({tok for tok in diff_text.replace("'", " ").replace('"', " ").split() if tok.startswith("B20_LF")})
    if not env_names:
        env_names = ["B20_LF_ENABLE", "B20_LF_FRAC", "B20_LF_RADIUS_FRAC", "B20_LF_ALPHA"]
    apply_status = apply_check.get("status", "unknown")
    lines = [
        "# B21.1 LF patch capture",
        "",
        "Status: generated by `scripts/b21/capture_lf_patch.py`.",
        "",
        "## Patch identity",
        "",
        f"- Repo root: `{repo_root}`",
        f"- DAPS root: `{daps_root}`",
        f"- Upstream ref: `{upstream_ref}`",
        f"- Diff paths: `{', '.join(diff_paths)}`",
        f"- Patch file: `{patch_path}`",
        f"- Clean apply check: `{apply_status}`",
        "",
        "## External DAPS git status",
        "",
        "```text",
        status_text.rstrip() or "(clean / no status output)",
        "```",
        "",
        "## Env-var semantics table draft",
        "",
        "Fill or verify this table after inspecting the source snippets below.",
        "",
        "| env var | default when unset | intended effect | notes |",
        "|---|---|---|---|",
    ]
    for env in env_names:
        lines.append(f"| `{env}` | TODO from source | TODO | TODO |")
    lines.extend(
        [
            "",
            "## Required math formula draft",
            "",
            "Executor/planner must fill this after source inspection:",
            "",
            "```text",
            "Given x0y, sigma/step index s, measurement y, mask M, and alpha,",
            "state the exact update x0y <- f(x0y, y, M, alpha).",
            "Also state whether M is pixel-domain or measurement-domain, whether the blend uses magnitudes or complex values, and the active step range.",
            "```",
            "",
            "## Source snippets around LF guards",
            "",
            snippets.rstrip() or "No B20_LF snippets found in requested files.",
            "",
            "## Patch diff",
            "",
            f"Full diff saved at `{patch_path}`.",
            "",
            "## Apply-check details",
            "",
            "```json",
            json.dumps(apply_check, indent=2, sort_keys=True),
            "```",
            "",
            "## Next action",
            "",
            "After running this helper, paste the report and/or source snippets back into the executor chat. The executor will write the exact formula and update the registry row `LF_v1` only after confirming the guard/default-off behavior.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="B21.1 LF patch capture helper")
    ap.add_argument("--repo_root", default="/egr/research-pac/huang248/pr_diffusion_b19_solver")
    ap.add_argument("--daps_root", default="external/daps")
    ap.add_argument("--upstream_ref", default="e7a77d0")
    ap.add_argument("--diff_paths", default="sampler.py,posterior_sample.py")
    ap.add_argument("--patch_path", default="docs/b21/patches/daps_b20_lf_guidance.patch")
    ap.add_argument("--report_path", default="docs/b21/b21_1_lf_patch_capture.md")
    ap.add_argument("--outdir", default="/egr/research-pac/huang248/outputs/pr_diffusion/b21_solver/B21_1_lf_patch_capture")
    ap.add_argument("--clean_check_dir", default="")
    ap.add_argument("--refresh_clean_check_dir", action="store_true")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    daps_root = (repo_root / args.daps_root).resolve() if not Path(args.daps_root).is_absolute() else Path(args.daps_root).resolve()
    diff_paths = split_items(args.diff_paths)
    patch_path = (repo_root / args.patch_path).resolve() if not Path(args.patch_path).is_absolute() else Path(args.patch_path).resolve()
    report_path = (repo_root / args.report_path).resolve() if not Path(args.report_path).is_absolute() else Path(args.report_path).resolve()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    code, status_out, status_err = run(["git", "status", "--short"], cwd=daps_root)
    status_text = status_out + ("\nSTDERR:\n" + status_err if status_err else "")

    diff_cmd = ["git", "diff", args.upstream_ref, "--", *diff_paths]
    code, diff_out, diff_err = run(diff_cmd, cwd=daps_root)
    diff_text = diff_out + ("\nSTDERR:\n" + diff_err if diff_err else "")
    write_text(patch_path, diff_text)
    write_text(outdir / "external_daps_status.txt", status_text)
    write_text(outdir / "diff_command.txt", " ".join(diff_cmd) + "\n")

    snippets = collect_env_snippets(daps_root, diff_paths)
    write_text(outdir / "lf_source_snippets.md", snippets)

    apply_check = maybe_clean_apply_check(
        daps_root=daps_root,
        upstream_ref=args.upstream_ref,
        patch_path=patch_path,
        clean_check_dir=args.clean_check_dir,
        refresh=bool(args.refresh_clean_check_dir),
    )
    write_text(outdir / "apply_check.json", json.dumps(apply_check, indent=2, sort_keys=True) + "\n")

    report = render_report(
        repo_root=repo_root,
        daps_root=daps_root,
        upstream_ref=args.upstream_ref,
        diff_paths=diff_paths,
        patch_path=patch_path,
        status_text=status_text,
        diff_text=diff_text,
        snippets=snippets,
        apply_check=apply_check,
    )
    write_text(report_path, report + "\n")
    print(f"[write] {patch_path}")
    print(f"[write] {outdir / 'lf_source_snippets.md'}")
    print(f"[write] {outdir / 'apply_check.json'}")
    print(f"[write] {report_path}")


if __name__ == "__main__":
    main()
